version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: hrms-backend
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    networks:
      - hrms-net

  postgres:
    image: postgres:16
    container_name: hrms-postgres
    restart: always
    environment:
      POSTGRES_USER: hrms_user
      POSTGRES_PASSWORD: hrms_password
      POSTGRES_DB: hrms_saas_db_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hrms-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hrms_user -d hrms_saas_db_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: hrms-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hrms.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - hrms-net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  hrms-net:

volumes:
  postgres_data:
  pgadmin_data:
